# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='traffic.proto',
  package='sim_msg',
  syntax='proto3',
  serialized_pb=_b('\n\rtraffic.proto\x12\x07sim_msg\"Y\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01t\x18\x02 \x01(\x01\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\x0f\n\x07heading\x18\x05 \x01(\x01\x12\t\n\x01v\x18\x06 \x01(\x01\x12\t\n\x01\x61\x18\x07 \x01(\x01\"\x15\n\x07\x45goInfo\x12\n\n\x02id\x18\x01 \x01(\x05\"H\n\x07Traffic\x12\x1a\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\x0c.sim_msg.Car\x12!\n\x07\x65goinfo\x18\x02 \x01(\x0b\x32\x10.sim_msg.EgoInfob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAR = _descriptor.Descriptor(
  name='Car',
  full_name='sim_msg.Car',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sim_msg.Car.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='sim_msg.Car.t', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='sim_msg.Car.x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='sim_msg.Car.y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='sim_msg.Car.heading', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='sim_msg.Car.v', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a', full_name='sim_msg.Car.a', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=115,
)


_EGOINFO = _descriptor.Descriptor(
  name='EgoInfo',
  full_name='sim_msg.EgoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sim_msg.EgoInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=138,
)


_TRAFFIC = _descriptor.Descriptor(
  name='Traffic',
  full_name='sim_msg.Traffic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cars', full_name='sim_msg.Traffic.cars', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egoinfo', full_name='sim_msg.Traffic.egoinfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=212,
)

_TRAFFIC.fields_by_name['cars'].message_type = _CAR
_TRAFFIC.fields_by_name['egoinfo'].message_type = _EGOINFO
DESCRIPTOR.message_types_by_name['Car'] = _CAR
DESCRIPTOR.message_types_by_name['EgoInfo'] = _EGOINFO
DESCRIPTOR.message_types_by_name['Traffic'] = _TRAFFIC

Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), dict(
  DESCRIPTOR = _CAR,
  __module__ = 'traffic_pb2'
  # @@protoc_insertion_point(class_scope:sim_msg.Car)
  ))
_sym_db.RegisterMessage(Car)

EgoInfo = _reflection.GeneratedProtocolMessageType('EgoInfo', (_message.Message,), dict(
  DESCRIPTOR = _EGOINFO,
  __module__ = 'traffic_pb2'
  # @@protoc_insertion_point(class_scope:sim_msg.EgoInfo)
  ))
_sym_db.RegisterMessage(EgoInfo)

Traffic = _reflection.GeneratedProtocolMessageType('Traffic', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFIC,
  __module__ = 'traffic_pb2'
  # @@protoc_insertion_point(class_scope:sim_msg.Traffic)
  ))
_sym_db.RegisterMessage(Traffic)


# @@protoc_insertion_point(module_scope)
